name: Music Release Tracker

on:
  # Schedule - every hour, 24/7 (at :15 past each hour)
  # PUBLIC REPOS = UNLIMITED FREE MINUTES! 🎉
  schedule:
    - cron: '15 * * * *'  # Runs at :15 every hour (12:15am, 1:15am, 2:15am, etc.)
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  check-releases:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run music tracker
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      run: |
        python music_tracker_cron.py
    
    - name: Upload tracked releases
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: tracked-releases
        path: tracked_releases.json
        retention-days: 30
